name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev

    - name: Configure CMake
      run: |
        mkdir cmake-build
        cmake -B cmake-build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: make -C cmake-build
